# Generated by Django 5.0.4 on 2024-04-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_slug_product_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
