# Generated by Django 5.0.4 on 2024-04-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_added'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
    ]
